[package]
name = "guess_number"
version = "0.1.0"
authors = ["Austin <austin.song@yuansuan.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"

